### ISSUE TITLE
When should you use this action over normal bash?

### ISSUE THREAD

**Issue by meiswjn** [Azure/powershell#12]
Hey,

First of all, thanks for all the great open source contributions - I really appreciate it.
I was wondering, how a best practice for this action in combination with a normal powershell would look like. How is this action better suited for commands than the normal powershell?

Thanks,
Jan

**Comment by arjgupta** [comment]
@meiswjn this action is meant to be used to run [Az PowerShell](https://github.com/Azure/azure-powershell) cmdlets. so you would use this action to run scripts that contains az powershell cmdlets. It can be used to run other powershell commands as well. The action provides a kind of run time environment for Azure powershell cmdlets to run by initializing a powershell session with the necessary credentials. That is all.
