### ISSUE TITLE
using Az.Resources module

### ISSUE THREAD

**Issue by sebastiangonsal** [Azure/powershell#13]
Using `azure/powershell@v1` module it gives error on using `Get-AzResources`:
```
The term 'Get-AzResource' is not recognized as the name of a
     | cmdlet, function, script file, or operable program. Check the
     | spelling of the name, or if a path was included, verify that
     | the path is correct and try again.
```

It seems like `Az.Resource` module is not installed in the powershell. How do i ensure that ? I have specified `azPSVersion` as `4.5.0` which should contain this module.

**Comment by AmrutaKawade** [comment]
where are you running your workflow? self hosted runner / github hosted runner?

**Comment by AmrutaKawade** [comment]
latest az module installed on hosted runner is 4.4.0. can you try with this version? available versions on runner are updated in this document https://github.com/Azure/powershell#available-versions-of-az-module-on-runner
