### ISSUE TITLE
Private hosted runners

### ISSUE THREAD

**Issue by pixie79** [Azure/powershell#14]
Hi

I would like to be able to run this action on my private azure windows deploy box like I could do with Azure pipelines. Is this an option? Or could be be added to the roadmap?

Thanks

Mark

**Comment by aksm-ms** [comment]
@pixie79 currently self-hosted runner is not supported for this action. I will mark this as an enhancement and we will work on it.

**Comment by aksm-ms** [comment]
@pixie79 Please let us know if there are any other queries.

**Comment by BALAGA-GAYATRI** [comment]
@pixie79 Adding this support is not in our roadmap now. If you have any PRs, feel free to contribute. Thank you!
