### ISSUE TITLE
Can we use Desktop instead of Core

### ISSUE THREAD

**Issue by bschenz-kr** [Azure/powershell#26]
I want to run a Set-AzureWebsite command, but get this:
The 'Set-AzureWebsite' command was found in the module 'Azure', but the module could not be loaded.
     | For more information, run 'Import-Module Azure'.

I add a command:
Import-Module -Name Azure -Verbose
now get this:
Could not load type 'System.Management.Automation.PSSnapIn' from assembly
     | 'System.Management.Automation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

according to this, it appears to be an issue of Powershell using dotnet core: https://github.com/seanmcne/Microsoft.Xrm.Data.PowerShell/issues/443

How can I specify to use Powershell Desktop?

**Comment by aksm-ms** [comment]
@bschenz-kr Currently the action only supports powershell core.
Can you try using "Set-AzWebApp" instead of Set-AzureWebsite?

**Comment by aksm-ms** [comment]
@bschenz-kr Please let me know if you are facing any other issues.

**Comment by bschenz-kr** [comment]
The Set-AzWebApp does not allow setting of -SlotStickySettings like the Set-AzureWebsite does

**Comment by aksm-ms** [comment]
@bschenz-kr Currently this action does not support PowerShell Desktop, only powershell core is supported. Closing the issue.
