### ISSUE TITLE
Question: Controlling the Log level

### ISSUE THREAD

**Issue by dkirrane** [Azure/powershell#41]
By default I get a lot of DEBUG logs in the action output. e.g.

```
DEBUG: Sought all Az modules and got latest version 6.1.0
```

Is it possible to control the log level?

**Comment by BALAGA-GAYATRI** [comment]
Hey @dkirrane. Ideally this action should not give you debug logs unless you have set the parameter `ACTIONS_STEP_DEBUG
` as `true` in your secrets.  Please check that parameter. If this action giving debug logs, you may raise your issue in that particular action repository. This repository deals with azure/powershell action only.

**Comment by BALAGA-GAYATRI** [comment]
Closing this issue. Feel free to reopen the issue if it is showing debug logs even after trying out above solution and attach screenshots of the output /workflow . We shall investigate it accordingly.
