### ISSUE TITLE
Support setting working-directory

### ISSUE THREAD

**Issue by dkirrane** [Azure/powershell#46]
Could this action support setting the `working-directory`

Similar to the run action https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun

**Comment by AjayKaleMS** [comment]
@dkirrane - Can you try with `cd $your_directory` inside `inlineScript  `? For example -
```
 with:
        inlineScript: |
          cd temp
          Get-AzVM -ResourceGroupName "ResourceGroup11"
        azPSVersion: "latest"
```
This will execute your script inside temp directory

**Comment by AjayKaleMS** [comment]
@dkirrane - We hope things are working fine at your end related with this issue. Hence we are closing this thread. 
Fell free to reopen the issue in case you encounter it again.
Thanks.
