### ISSUE TITLE
Cannot find type [Microsoft.Open.AzureAD.Model.AppRole]

### ISSUE THREAD

**Issue by gfrid** [Azure/powershell#54]
Is there anyway to use AzureAD module in this? Seems that the module is installed but can not be used properly 
AzureAD needs to run in powershell.exe v2 and actions run it as pwsh.exe v.7

Caught the exception System.Management.Automation.PSArgumentException: Cannot find type [Microsoft.Open.AzureAD.Model.AppRole]: verify that the assembly containing this type is loaded.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

https://docs.microsoft.com/en-us/answers/questions/903709/cloudshell.html

**Comment by BALAGA-GAYATRI** [comment]
Can you share your workflow and error logs for better understanding?

**Comment by YanaXu** [comment]
Hi @gfrid,  this action is for Azure PowerShell. AzureAD is not included. You can refer to https://learn.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0 for details.

**Comment by YanaXu** [comment]
Hi @gfrid, I'll close this issue due to the reason in my last comment. Feel free to create a new one if you have more questions.
