### ISSUE TITLE
Include CodeQl @v2 Workflow

### ISSUE THREAD

**Issue by jbenaventem** [Azure/powershell#60]
- Include a Security workflow based on CodeQL Actions @v2

**Comment by BALAGA-GAYATRI** [comment]
Hi @jbenaventem , please explain the issue with the proposed solution in detail for better understanding

**Comment by jbenaventem** [comment]
Hi  @BALAGA-GAYATRI 

You can see the modified files on the associated pull request #61

To can use this action in our organizations we should check several security checks, and we need that the actions verified these controls successfully.

For that, we use CodeQL and dependaboot tools in a similar way that you in another action, for example azure login . Is for that we've seen that the action could have a codeql YAML file to check the security controls

Apologies, but my English is not as good as I'd Like it

**Comment by BALAGA-GAYATRI** [comment]
Thanks for the clarification. We shall review and merge it.

**Comment by BALAGA-GAYATRI** [comment]
Added the workflow.
