### ISSUE TITLE
Failed initializing Az Module

### ISSUE THREAD

**Issue by deploymentgithub** [Azure/powershell#75]
On self hosted runner Windows 10

`Run azure/powershell@v1
Validating inputs
Module Az latest installed from hostedAgentFolder
Initializing Az Module
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command Test-Path (Join-Path C:\Modules az_*)
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command "try ***
            $ErrorActionPreference = \"Stop\"
            $WarningPreference = \"SilentlyContinue\"
            $output = @***
            $data = Get-Module -Name Az -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = \"true\"
        ***
        catch ***
            $output['Error'] = $_.exception.Message
        ***
        return ConvertTo-Json $output"
False

  "Error": "You cannot call a method on a null-valued expression."

`

**Comment by BALAGA-GAYATRI** [comment]
@deploymentgithub Can you please confirm if you are still facing the issue? Also do let us know if this error has up all of a sudden or you are trying it for the first time?
