### ISSUE TITLE
Azure powershell support on self-hosted runners

### ISSUE THREAD

**Issue by Mu-Reslife** [Azure/powershell#82]
Hi Team,

The README.md states that Azure/PowerShell action is unsupported on self-hosted runners. Is it still the case?
We are trying to get this work on our Ubuntu self-hosted runners hosted on AWS and it fails.

Thanks
Mu.

**Comment by YanaXu** [comment]
Hi @Mu-Reslife , "Ubuntu self-hosted runners" should be supported. Could you provide your workflow file and the error debug logs for further analysis?

**Comment by YanaXu** [comment]
It's all supported now. Please try `v1` now.
