### ISSUE TITLE
Initializing Az Module - Error

### ISSUE THREAD

**Issue by extravio** [Azure/powershell#88]
Hi,

I have a self-hosted runner on RHEL 9 with:
- powershell 7.2.16 (also tried 7.3) 
- the AZ module

and I get the following error when executing the azure/powershell action:
**Error: You cannot call a method on a null-valued expression.**

```sh
Run azure/powershell@v1
[...]
Validating inputs
Module Az latest installed from hostedAgentFolder
Initializing Az Module
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command Test-Path (Join-Path /usr/share az_*)
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command try ***
            $ErrorActionPreference = "Stop"
            $WarningPreference = "SilentlyContinue"
            $output = @***
            $data = Get-Module -Name Az -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = "true"
        ***
        catch ***
            $output['Error'] = $_.exception.Message
        ***
        return ConvertTo-Json $output
False
***
  "Error": "You cannot call a method on a null-valued expression."
***
Error: Error: You cannot call a method on a null-valued expression.
```

I previously had the same configuration on Ubuntu and it was working fine.

Any ideas?

**Comment by YanaXu** [comment]
Hi @extravio, could you login to your self-hosted runner machine, open powershell, and run the following cmdlets?
```powershell
$data = Get-Module -Name Az -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
Write-Host $data.Version.ToString()
```

**Comment by extravio** [comment]
Hi @YanaXu , 
Thanks for the quick reply. I made me realize that it was a problem with permissions.
The user on my runner did not have access to the folder where the modules were installed. 
`chmod -R 755 /usr/local/share/powershell/`
fixed my issue
