### ISSUE TITLE
When us the AzPSVersion: latest flag Az version 9 is used instead of version 11

### ISSUE THREAD

**Issue by NickSt** [Azure/powershell#94]
the latest flag does not seem to use the latest version of the az ps module.  It produces a warning on each running stating version 9 is being ran.

**Comment by YanaXu** [comment]
Hi @NickSt , could you provide the sample workflow file, debug log and details about your runners? Do you use a self-hosted runner or a GitHub-hosted runner?

**Comment by NickSt** [comment]
Hi YanaXu

Using github-hosted runners

The job looks like this:

`jobs:
  build:
    name: Build
    runs-on: windows-latest
    environment: <customID>
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PRIMARY }}
        enable-AzPSSession: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Calculate Variables
      id: data
      shell: pwsh
      run: |
            <script stuff here>

    - name: Build
      uses: azure/powershell@v1
      with: 
        inlineScript: <script runs here>
        azPSVersion: latest
        failOnStandardError: true`

**Comment by YanaXu** [comment]
@NickSt , the `latest` azPSVersion actually means the pre-installed Az module version on the GitHub-hosted runners, which is `9.3.0`. Before it's upgraded to the latest one on PSGallery, could you update your workflow file to use like `azPSVersion: 11.0.0`?

**Comment by YanaXu** [comment]
@NickSt , I'll close this issue now. Please feel free to reopen it if you still have questions on this.
