### ISSUE TITLE
Node.js 16 is deprecated please update to version 20

### ISSUE THREAD

**Issue by erikverwer** [Azure/powershell#97]
When using `azure/powershell@v1` Github Workflow gives a warning:
![image](https://github.com/Azure/powershell/assets/24406274/60cd0771-cc3f-4269-918a-ab41d49e9756)

[Github Blog](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20)

Same issue on `azure/login@v1` https://github.com/Azure/login/issues/357

Please update the actions to Node.js version 20

**Comment by Kaibaer** [comment]
Where is the specific problem, @erikverwer?, other than to migrate to the use of nodejs v20?

The blog post points to their documentation:
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

They especially mention:

```
runs:
  using: 'node20'
  [whatever precedes or follows in your actions]
```

**Comment by erikverwer** [comment]
No specific problem, I could have done the contribution myself ;-)

**Comment by merill** [comment]
Can this be fixed please thanks?

**Comment by YanaXu** [comment]
@merill we're planning a major release (**v2**) for this. Please wait for it.

**Comment by YanaXu** [comment]
[Azure PowerShell Action v2](https://github.com/Azure/powershell/releases/tag/v2) is released. Please try it.
